WebApplication1/Areas/AnyarAdmin/ViewModels/Team/TeamMemberVM.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata;

namespace WebApplication1.Areas.AnyarAdmin.ViewModels.Team;

public class TeamMemberVM
{

    [Required, MaxLength(50)]
    public string? Name { get; set; }
    [Required, MaxLength(100)]
    public string? Position { get; set; }
    [Required, MaxLength(250)]
    public string? Description { get; set; }
    [Required]
    public IFormFile Image { get; set; }
}

WebApplication1/Areas/AnyarAdmin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Areas.AnyarAdmin.Controllers;
[Area("AnyarAdmin")]
public class DashboardController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

WebApplication1/Areas/AnyarAdmin/Controllers/TeamMemberController.cs
using Core.Entities;
using DataAccess.Contexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using WebApplication1.Areas.AnyarAdmin.ViewModels.Team;
using WebApplication1.Utilities;

namespace WebApplication1.Areas.AnyarAdmin.Controllers;
[Area("AnyarAdmin")]
public class TeamMemberController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _env;

    public TeamMemberController(AppDbContext context, IWebHostEnvironment env)
    {
        _context = context;
        _env = env;
    }

    public IActionResult Index()
    {
        return View(_context.TeamMembers);
    }
    public async Task<IActionResult> Detail(int id)
    {
        var model = await _context.TeamMembers.FindAsync(id);
        if (model == null) return NotFound();
        return View(model);
    }
    public IActionResult Create(int id)
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(TeamMemberVM teamVM)
    {
        if (!ModelState.IsValid) return View(teamVM);
        if (teamVM.Image == null)
        {
            ModelState.AddModelError("Image", "Please select the image");
            return View(teamVM);
        }
        if (!teamVM.Image.CheckFileSize(100))
        {
            ModelState.AddModelError("Image", "Please choose correct file size");
            return View(teamVM);
        }
        if (!teamVM.Image.CheckFileFormat("image/"))
        {
            ModelState.AddModelError("Image", "Plase choose correct file format");
            return View(teamVM);
        }
        var filename = string.Empty;
        try
        {
            filename = await teamVM.Image.CopyFileAsync(_env.WebRootPath, "assets", "img", "team");
        }
        catch (Exception)
        {
            return View(teamVM);
        }
        TeamMember member = new()
        {
            Image = filename,
            Name = teamVM.Name,
            Position = teamVM.Position,
            Description = teamVM.Description
        };
        await _context.AddAsync(member);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int id)
    {
        var model = await _context.TeamMembers.FindAsync(id);
        if (model == null) return NotFound();
        return View(model);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        var model=await _context.TeamMembers.FindAsync(id);
        if (model == null) return NotFound();
        Helper.DeleteFile(_env.WebRootPath, "assets", "img", "team", model.Image);
        _context.TeamMembers.Remove(model);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

WebApplication1/Controllers/HomeController.cs
using DataAccess.Contexts;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.TeamMembers);
        }
    }
}

WebApplication1/Areas/AnyarAdmin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Dashboard</h1>

WebApplication1/Areas/AnyarAdmin/Views/TeamMember/Create.cshtml
@using WebApplication1.Areas.AnyarAdmin.ViewModels.Team
@model TeamMemberVM
@{
    ViewData["Title"] = "Create";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Team Member</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label>Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <input asp-for="Image" class="form-control" placeholder="Image">
                    <span class="text-danger" asp-validation-for="Image"></span>
                </div>
                <div class="form-group">
                    <label>Position</label>
                    <input asp-for="Position" class="form-control" placeholder="Position">
                    <span class="text-danger" asp-validation-for="Position"></span>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input asp-for="Description" class="form-control" placeholder="Description">
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

WebApplication1/Areas/AnyarAdmin/Views/TeamMember/Delete.cshtml
@model TeamMember
@{
    ViewData["Title"] = "Delete";
}

<div class="col-6">
    <h1>Delete</h1>
    <h3>@Model.Name</h3>
    <p>@Model.Description</p>
    <p>@Model.Position</p>
    <img src="~/asssets/img/team/@Model.Image" height="50px" />
</div>
<div class="col-12 mt-3">
    <form method="post" enctype="multipart/form-data">
        <button class="btn btn-danger" asp-action="Delete">Delete</button>
    </form>
    <a asp-action="Index" class="btn btn-primary">Go Back!</a>  
    
</div>

WebApplication1/Areas/AnyarAdmin/Views/TeamMember/Detail.cshtml
@model TeamMember
@{
    ViewData["Title"] = "Detail";
}
<div class="col-6">
    <h1>Detail</h1>
    <h3>@Model.Name</h3>
    <p>@Model.Position</p>
    <p>@Model.Description</p>
    <img src="~/assets/img/team/@Model.Image" height="50px" />
    <a asp-action="Index" class="btn btn-primary">Go Back!</a>
</div>

WebApplication1/Areas/AnyarAdmin/Views/TeamMember/Index.cshtml
@model IEnumerable<TeamMember>
@{
    ViewData["Title"] = "Index";
}
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Team Members</h4>
            <a asp-action="Create">Create member</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="py-1">
                                    <img src="~/assets/img/team/@item.Image" alt="Image">
                            </td>
                                <td>@item.Name</td>
                                <td>@item.Position</td>
                                <td>
                                    <a asp-area="AnyarAdmin" asp-controller="TeamMember" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-primary">Detail</a>
                                    <a asp-area="AnyarAdmin" asp-controller="TeamMember" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Update</a>
                                    <a asp-area="AnyarAdmin" asp-controller="TeamMember" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Anyar Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Anyar - v4.10.0
    * Template URL: https://bootstrapmade.com/anyar-free-multipurpose-one-page-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="fixed-top d-flex align-items-center ">
        <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope-fill"></i><a href="mailto:contact@example.com">info@example.com</a>
                <i class="bi bi-phone-fill phone-icon"></i> +1 5589 55488 55
            </div>
            <div class="cta d-none d-md-block">
                <a href="#about" class="scrollto">Get Started</a>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center ">
        <div class="container d-flex align-items-center justify-content-between">

            <h1 class="logo"><a href="index.html">Anyar</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href=index.html" class="logo"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>
                    <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
            @RenderBody()
    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-newsletter">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    </div>
                    <div class="col-lg-6">
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h4>Contact Us</h4>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>

                    </div>

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>About Anyar</h3>
                        <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Anyar</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/anyar-free-multipurpose-one-page-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>